[package]
name = "qi-tools"
description = "Command-line tools for `qi` spaces: the `qi-cli` command"

edition.workspace = true
license.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = { workspace = true }
base64 = "0.23.1"
clap = { workspace = true }
colored = { workspace = true }
futures = { workspace = true }
libqi = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "time"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }

[[bin]]
name = "qi-cli"
path = "src/main.rs"
