[package]
name = "qi"
description = ""

edition.workspace = true
license-file.workspace = true
authors.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = { workspace = true }
derive_more = { workspace = true }
bytes = { workspace = true }
either = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
pin-project-lite = { workspace = true }
qi-format = { path = "../qi-format" }
qi-macros = { path = "../qi-macros" }
qi-messaging = { path = "../qi-messaging" }
qi-value = { path = "../qi-value" }
sealed = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
ouroboros = "0.18.5"

[dev-dependencies]
assert_matches = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time", "sync"] }
tokio-test = { workspace = true }
tracing-subscriber = { workspace = true }
